# Example configuration file for pipeline processing

16S:
  forward_primer: "RGTTYGATYMTGGCTCAG"
  reverse_primer: "RGYTACCTTGTTACGACTT"
  # For non-default barcode files, provide absolute filepaths
  forward_barcodes: "barcodes96.fasta" 
  reverse_barcodes: "reverse_barcodes96.fasta"
  min_len: 1200
  max_len: 1700
  cores: 4

ITS:
  forward_primer: "TCCGTAGGTGAACCTGCGG"
  reverse_primer: "TCCTCCGCTTATTGATATGC"
  forward_barcodes: "barcodes96.fasta"
  reverse_barcodes: "reverse_barcodes96.fasta"
  min_len: 200
  max_len: 2000
  cores: 4

# Add additional project types as needed
